### ISSUE TITLE
The SSL certificate is invalid 

### ISSUE THREAD

**Issue by adrian-pistoleanu** [ajilach/clamav-rest#38]
Hello
I'm sending files to the api (Web API in Docker to ClamAv Docker) and it looks that the ClamAV image is missing a valid certificate so it won't accept requests.

The error that I'm getting is
[{System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.. The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors](url)

**Comment by adrian-pistoleanu** [comment]
Any update on this , please ?

Also, where is the SSL certificate located and how it can be updated with a valid one, please ?

**Comment by arizon-dread** [comment]
The SSL Certificate is valid until 2030, but the certificate doesn't contain any domain names. If you run this locally, you can create a localhost certificate [You can use the dotnet command for this](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-dev-certs). Then you can mount a volume on /etc/ssl/clamav mapping it to a folder with both the certificate file and the private key.

Here's a few examples on how to achieve that: 
Kubernetes

```yaml
#under your container for clamav-rest
    volumeMounts:
        - name: cert-secret
          mountPath: /etc/ssl/clamav-rest
#...
#Under deployment.spec.template.spec
      volumes:
      - name: cert
        secret:
          secretName: cert-secret
          items:
            - key: server.crt
              path: server.crt
            - key: server.key
              path: server.key
``` 
Note that the application expects these names, see [line 266](https://github.com/ajilach/clamav-rest/blob/master/clamrest.go)

Docker: 
```bash
docker run -p 9000:9000 -p 9443:9443 -d --name clamav-rest -v /absolute/path/to/folder:/etc/ssl/clamav-rest docker.io/ajilaag/clamav-rest:20240622
```
See documentation [clamav-rest container image](https://hub.docker.com/r/ajilaag/clamav-rest)
see official docker documentation on [how to handle volumes with docker ](https://docs.docker.com/storage/volumes/)

In the clamav-rest repository, there's a dockercompose file (the non-root one already has mounts), see that on how to get it running locally with docker-compose. 

Please also note that you have to create trust for the server cert in your client application, how this is done depends on your operating system or the operating system of the container your client is running on/in. 

[see this link for intro on how this works](https://www.baeldung.com/linux/ca-certificate-management)
